blank_issues_enabled: false
contact_links:
  - name: Payment Modules Support
    url: https://modstore.pro/authors/alroniks
    about: Please, create the ticket via the marketplace website to get professional support.
  - name: Premium MODX Support
    url: https://alroniks.com
    about: Premium MODX Support for agencies and independent developers from MODX core developer.
